module IRC
  module Constants
    MESSAGE_PART_SEPARATOR = ' ' #space
    COMMAND_PARAMETERS_MAX = 15
    PREFIX_INDICATOR = ':'
    TRAILING_PARAMETER_CHARACTER = ':'
    LINE_FEED_CHARACTER = 10.chr #line feed,new line
    CARRAGE_RETURN_CHARACTER = 13.chr #carrage return
    END_OF_MESSAGE_STRING = LINE_FEED_CHARACTER + CARRAGE_RETURN_CHARACTER
    MAX_MESSAGE_SIZE = 512
  end
end
